.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "SIP Call Control" "1" "Aug 13, 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
call\-control \- A SIP call control engine for OpenSIPS
.SH SYNOPSIS
.B call-control
.RI [ options ]
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
Call Control is a prepaid application that can be used together with the
OpenSIPS call_control module and the CDRTool rating engine to limit the
duration of SIP sessions based on a prepaid balance. It can also be used
to limit the duration of non-prepaid sessions to a predefined maximum
value.
.PP
Call Control achieves this by maintaining a timer for each session and
terminating the call if the session exceeds its allowed time limit or
if Call Control receives an external request to terminate the session.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show the program version.
.TP
.B \-\-systemd
Run the process as a systemd simple service and log to journal.
.TP
.B \-\-no\-fork
Run the process in the foreground and log to the terminal.
.TP
.B \-\-config\-dir=PATH
Set the configuration directory (default is \fB/etc/callcontrol\fP).
.TP
.B \-\-runtime\-dir=PATH
Set the runtime directory (default is \fB/run/callcontrol\fP).
.TP
.B \-\-debug
Enable verbose logging.
.TP
.B \-\-debug\-memory
Enable memory debugging.
.SH AUTHORS
Dan Pascu <dan@ag-projects.com>
.br
Lucian Stanescu <luci@ag-projects.com>.
