.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "SIP Call Control" "1" "May 15, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
call\-control \- the SIP call control application
.SH SYNOPSIS
.B call-control
.RI [ options ]
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
Call Control is a prepaid application that can be used together with
OpenSIPS call_control module and CDRTool rating engine to limit the duration
of SIP sessions based on a prepaid balance. It can also be used to limit the
duration of any session to a predefined maximum value without debiting a
balance.
.PP
Call Control achieves this by maintaining a timer for each session and
sending BYE messages to both SIP end-points, if the session exceeds its
maximum session limit or if the Call Control receives a command to
forcefully close the call from outside.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-\-no\-fork
Run the process in the foreground (for debugging).
.TP
.B \-\-pid=file
Set the proces pid file to \fB`file'\fP. If not specified the default
pid file is \fB/var/run/callcontrol/call\-control.pid\fP .
.SH AUTHORS
Dan Pascu <dan@ag-projects.com>
.br
Lucian Stanescu <luci@ag-projects.com>.
